Creacion del menu ,3 botones Jugar,Score,Controles
cesarrobertoruizmacias/Proyecto pull request #6
Opened 2021-06-06 04:17 UTC by cesarrobertoruizmacias

En el menu ahi tres botones Jugar, Score, Controles , la flecha selecciona la opción deseada se selecciona los botones con las flechas arriba ("UP") y abajo ("DOWN")

2021-06-08 15:03 UTC, iuresti requested changes

2021-06-08 15:03 UTC, iuresti commented on proyecto/Menu.java
> +        if(Greenfoot.isKeyDown("UP") && option!=0) {option--;}
Se que es tentador dejar código en una línea, pero no es buena práctica.. si usan el "Auto-layout" de greenfoot se los va a mover a múltiples líneas

2021-06-08 15:03 UTC, iuresti commented on proyecto/Menu.java
> +        if(option<0 && option==0) {option=0;}
no puede ser menor que cero e igual que cero a la vez .. este if siempre es false

2021-06-08 15:03 UTC, iuresti commented on proyecto/Menu.java
> +        if(option>1 && option==2) {option=2;}
revisa estos condicionales .. tal vez querías usar ||

2021-06-08 15:03 UTC, iuresti commented on proyecto/Menu.java
> +        if(option>0 && option<2)  {option=1;}
if(option == 1) es lo mismo es más simple

2021-06-13 05:08 UTC, iuresti approved these changes
Eliminen los archivos *. class y formateen su código

2021-06-13 18:44 UTC, WinEd73 reviewed
Ok

2021-06-13 18:46 UTC, merged